### ISSUE TITLE
How is this different from `stack new`

### ISSUE THREAD

**Issue by cies** [dbushenko/trurl#21]
Looks like a nice tool!

Maybe the README to set it apart from `stack new`, which seems to have largely the same objective.

BTW: I recently spoke to Snoyman and he seems to be willing to imcrease the feature set of `stack new`, so it might be possible to merge these projects (which I think could really suite newcomers).

**Comment by dbushenko** [comment]
Hi,

I don't expect Snoyman knows me or even would like to talk to me :-)

> > How is this different from `stack new`
> > This is the question I usually get :-) Let me explain you with examples.

1) Try creating a website template containing binary data (images, fonts, etc.). Stack uses one plain text file for the template, so managing binary data is just difficult. But this is trivial task with trurl.

2) Try creating your own repository for templates. If you wanna use stack -- you either submit your templates to central repository or do something non-trivial to not send them but still use. With trurl you just put them to $HOME/.trurl

Dmitry

**Comment by cies** [comment]
Ok. Just asking :) I think they are two apps in a very similar space.

Thanks for your explanation!
