### ISSUE TITLE
Raise base bound?

### ISSUE THREAD

**Issue by FranklinChen** [dbushenko/trurl#3]
Can you raise the base bound to support GHC 7.10.1?

**Comment by dbushenko** [comment]
Yes, sure. Will do this today and bump the new version with latest changes.

**Comment by dbushenko** [comment]
Fixed, please have a look.

**Comment by FranklinChen** [comment]
Thanks, I can run it now.

**Comment by dbushenko** [comment]
Just let me know if any other features needed!
